# Forward every Hassio notification to notify service
- alias: Forward persistent notifications
  initial_state: "on"
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  action:
    - service: notify.slack
      data_template:
        message: >-
          {% set message = trigger.event.data.service_data.message %}
          {% if 'login attempt' in message|lower %}
            {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
          {% else %}
            {{ message }}
          {% endif %}

# Restart Home Assistant every night
- alias: Restart Home Assistant every night so presence detection via ping keeps working
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    - service: persistent_notification.create
      data_template:
        message: "Home Assistant wordt opnieuw gestart. Dit is nodig omdat anders de presence detectie via ping niet blijft werken."
        title: "Herstart Home Assistant"
    - delay: 0:00:30 #so notify can be send before restart
    - service: homeassistant.restart