# Zet licht aan 's avonds
- alias: Licht (gedimd) aan half uur voor zonsondergang
  trigger:
    event: sunset
    offset: -0:30
    platform: sun
  condition: []
  action:
    service: scene.turn_on
    entity_id: scene.gedimd

- alias: Licht (minder gedimd) bij zonsondergang
  trigger:
    event: sunset
    offset: -0:00
    platform: sun
  condition: []
  action:
    service: scene.turn_on
    entity_id: scene.conversatie

# Dim lichten als TV aangezet (via Chromecast)
- alias: "Dim lichten als TV aangezet"
  trigger:
    - platform: state
      entity_id: media_player.chromecast_jonkertjes
      from: "unavailable"
      to: "off"
  condition:
    - condition: state
      entity_id: group.woonkamer
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.film
    - service: persistent_notification.create
      data_template:
        message: "Scene film geactiveerd. Trigger: lichten in woonkamer aan, TV aangezet"
        title: "TV aangezet"


# Licht aan als minder dan 10 lux in woonkamer
# - alias: Licht aan als minder dan 15 lux in woonkamer
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.lightlevel_8
#     below: 15
#     for: "00:01:00"
#   condition: 
#   action:
#     service: scene.turn_on
#     entity_id: scene.film