# Licht aan als donker OF sunset
- alias: Scene gedimd als donker OF half uur voor sunset
  trigger:  
    - platform: sun
      event: sunset
      offset: -0:30
    - platform: numeric_state
      entity_id: sensor.lightlevel_8
      below: 15
      for: "00:00:30"
  condition: 
    condition: state
    entity_id: group.jonkertjes
    state: "home"
  action:
    - service: scene.turn_on
      entity_id: scene.gedimd
    - service: persistent_notification.create
      data_template:
        message: "Scene gedimd geactiveerd. 
        Trigger: half uur voor sunset {{ states.sun.sun.state }} OF low lux {{ states.sensor.lightlevel_8.state }}, iemand van Jonkertjes thuis"
        title: "Licht aangepast"


- alias: Scene conversatie als donker OF sunset
  trigger:
    - platform: sun
      event: sunset
      offset: 0:00
    - platform: numeric_state
      entity_id: sensor.lightlevel_8
      below: 5
      for: "00:00:30"
  condition: 
    condition: state
    entity_id: group.jonkertjes
    state: "home"
  action:
    - service: scene.turn_on
      entity_id: scene.conversatie
    - service: persistent_notification.create
      data_template:
        message: "Scene conversatie geactiveerd. 
        Trigger: sunset {{ states.sun.sun.state }} OF low lux {{ states.sensor.lightlevel_8.state }}, iemand van Jonkertjes thuis"
        title: "Licht aangepast"
  

# Dim licht als TV aangezet (via Chromecast)
- alias: "Dim lichten als TV aangezet"
  trigger:
    - platform: state
      entity_id: media_player.chromecast_jonkertjes
      from: "unavailable"
      to: "off"
  condition:
    - condition: state
      entity_id: group.woonkamer
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.film
    - service: persistent_notification.create
      data_template:
        message: "Scene film geactiveerd. Trigger: lichten in woonkamer aan, TV aangezet"
        title: "TV aangezet"
