# Zet input_boolean "Jonkertjes slapen" 's ochtends op off, zodat lampen automatisch reageren
- alias: Zet indicatie Jonkertjes slapen 's morgens uit
  trigger:
    - platform: time
      at: "06:55:00"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleeping
    - service: persistent_notification.create
      data_template:
        message: "Indicatie Jonkertjes slapen uitgezet. Triggers op lampen werken vanaf nu weer."
        title: "Indicatie Jonkertjes slapen uitgezet."

# Zet lichten uit ls input_boolean "Jonkertjes slapen" van off naar on gaat
- alias: Zet lichten uit als indicatie Jonkertjes slapen van off naar on
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: group.woonkamer
    - service: scene.turn_on
      entity_id: scene.nachtstand_boven
    - service: persistent_notification.create
      data_template:
        message: "Indicatie Jonkertjes slapen aangezet. Lampen in de group.woonkamer worden uitgezet."
        title: "Jonkertjes gaan slapen"

# Zet lichten aan als beweging en donker in de woonkamer
- alias: Scene conversatie als donker EN beweging in woonkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_9
      to: 'on'
  condition: 
    - condition: numeric_state
      entity_id: sensor.lightlevel_8
      below: 10 
    - condition: state
      entity_id: group.jonkertjes
      state: "home"
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: group.woonkamer
      state: 'off'            # only if lights not already on (i.e. manual selected scene)
  action:
    - service: scene.turn_on
      entity_id: scene.conversatie
    - service: persistent_notification.create
      data_template:
        message: "Scene Conversatie geactiveerd. 
        Trigger: Beweging in de woonkamer EN lux {{ states.sensor.lightlevel_8.state }} is lager dan 10 (lux overkapping is{{ states.sensor.lightlevel_12.state }}) EN iemand van Jonkertjes thuis EN Jonkertjes slapen niet"
        title: "Licht aangepast"
  

# Zet lichten uit als weer lichter
- alias: Zet lichten uit als licht genoeg in de woonkamer
  trigger:
    - platform: numeric_state
      entity_id: sensor.lightlevel_8
      above: 10
  condition: 
    - condition: state
      entity_id: group.woonkamer
      state: 'on'     
    - condition: numeric_state
      entity_id: sensor.lightlevel_12
      above: 120      
  action:
    - service: light.turn_off
      entity_id: group.woonkamer
    - service: persistent_notification.create
      data_template:
        message: "Lichten in woonkamer uitgezet. Trigger: lux {{ states.sensor.lightlevel_8.state }} woonkamer is groter dan 10 EN lux {{ states.sensor.lightlevel_12.state }} overkapping is groter dan 120"
        title: "Lichten uitgezet"

# Activeer scene als op Tradfri knop gedrukt -- DOWN
- alias: Activeer scene Film als Tradfri Down 
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'down'
  action:
    - service: scene.turn_on
      entity_id: scene.film
    - service: persistent_notification.create
      data_template:
        message: "Scene Film geactiveerd. Trigger: knop Down op Tradfri remote control."
        title: "Scene"
  
# Activeer scene als op Tradfri knop gedrukt -- UP
- alias: Activeer scene Film als Tradfri Up 
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'up'
  action:
    - service: scene.turn_on
      entity_id: scene.gedimd
    - service: persistent_notification.create
      data_template:
        message: "Scene Gedimd geactiveerd. Trigger: knop Up op Tradfri remote control."
        title: "Scene"

# Activeer scene als op Tradfri knop gedrukt -- NEXT
- alias: Activeer scene Film als Tradfri Next 
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'next'
  action:
    - service: scene.turn_on
      entity_id: scene.conversatie
    - service: persistent_notification.create
      data_template:
        message: "Scene Conversatie geactiveerd. Trigger: knop Next op Tradfri remote control."
        title: "Scene"

# Activeer scene als op Tradfri knop gedrukt -- PREVIOUS
- alias: Activeer scene Film als Tradfri Previous 
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'previous'
  action:
    - service: scene.turn_on
      entity_id: scene.verjaardag
    - service: persistent_notification.create
      data_template:
        message: "Scene Verjaardag geactiveerd. Trigger: knop Previous op Tradfri remote control."
        title: "Scene"

# Zet lichten uit als op Tradfri knop gedrukt -- TOGGLE
- alias: Lichten woonkamer uit als Tradfri Toggle Off
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'toggle'
  condition: 
    - condition: state
      entity_id: group.woonkamer
      state: 'on'     
  action:
    - service: light.turn_off
      entity_id: group.woonkamer
    - service: persistent_notification.create
      data_template:
        message: "Lichten woonkamer uitgezet. Trigger: knop Toggle op Tradfri remote control."
        title: "Lights"

# Zet lichten aan als op Tradfri knop gedrukt -- TOGGLE
- alias: Lichten woonkamer uit als Tradfri Toggle On
  trigger:
    - platform: state
      entity_id: sensor.tradfri_remote_control
      to: 'toggle'
  condition: 
    - condition: state
      entity_id: group.woonkamer
      state: 'off'     
  action:
    - service: light.turn_on
      entity_id: group.woonkamer
    - service: persistent_notification.create
      data_template:
        message: "Lichten woonkamer aangezet. Trigger: knop Toggle op Tradfri remote control."
        title: "Lights"
