# Zet input_boolean "Jonkertjes slapen" 's ochtends op off, zodat lampen automatisch reageren
- alias: Zet indicatie Jonkertjes slapen 's morgens uit
  trigger:
    - platform: time
      at: "06:55:00"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleeping
    - service: persistent_notification.create
      data_template:
        message: "Indicatie Jonkertjes slapen uitgezet. Triggers op lampen werken vanaf nu weer."
        title: "Indicatie Jonkertjes slapen uitgezet."

# Zet lichten uit ls input_boolean "Jonkertjes slapen" van off naar on gaat
- alias: Zet lichten uit als indicatie Jonkertjes slapen van off naar on
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: group.woonkamer
    - service: scene.turn_on
      entity_id: scene.nachtstand_boven
    - service: persistent_notification.create
      data_template:
        message: "Indicatie Jonkertjes slapen aangezet. Lampen in de group.woonkamer worden uitgezet."
        title: "Jonkertjes gaan slapen"

# Zet lichten aan als beweging en donker in de woonkamer
- alias: Scene conversatie als donker EN beweging in woonkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_9
      to: 'on'
  condition: 
    - condition: numeric_state
      entity_id: sensor.lightlevel_8
      below: 10 
    - condition: state
      entity_id: group.jonkertjes
      state: "home"
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: group.woonkamer
      state: 'off'            # only if lights not already on (i.e. manual selected scene)
  action:
    - service: scene.turn_on
      entity_id: scene.conversatie
    - service: persistent_notification.create
      data_template:
        message: "Scene Conversatie geactiveerd. 
        Trigger: Beweging in de woonkamer EN lux {{ states.sensor.lightlevel_8.state }} is lager dan 10 (lux overkapping is{{ states.sensor.lightlevel_12.state }}) EN iemand van Jonkertjes thuis EN Jonkertjes slapen niet"
        title: "Licht aangepast"
  

# Zet lichten uit als weer lichter
- alias: Zet lichten uit als licht genoeg in de woonkamer
  trigger:
    - platform: numeric_state
      entity_id: sensor.lightlevel_8
      above: 10
  condition: 
    - condition: state
      entity_id: group.woonkamer
      state: 'on'     
    - condition: numeric_state
      entity_id: sensor.lightlevel_12
      above: 120      
  action:
    - service: light.turn_off
      entity_id: group.woonkamer
    - service: persistent_notification.create
      data_template:
        message: "Lichten in woonkamer uitgezet. Trigger: lux {{ states.sensor.lightlevel_8.state }} woonkamer is groter dan 10 EN lux {{ states.sensor.lightlevel_12.state }} overkapping is groter dan 120"
        title: "Lichten uitgezet"
 

# # Dim licht als TV aangezet (via Chromecast)
# - alias: "Dim lichten als TV aangezet"
#   trigger:
#     - platform: state
#       entity_id: media_player.chromecast_jonkertjes
#       from: "unavailable"
#       to: "off"
#       for:
#         hours: 0
#         minutes: 2
#         seconds: 0
#   condition:
#     - condition: state
#       entity_id: group.woonkamer
#       state: "on"
#   action:
#     - service: scene.turn_on
#       entity_id: scene.film
#     - service: persistent_notification.create
#       data_template:
#         message: "Scene film geactiveerd. Trigger: lichten in woonkamer aan, TV aangezet"
#         title: "TV aangezet"
