# Zet licht aan 's avonds
- alias: Licht (gedimd) aan half uur voor zonsondergang
  trigger:
    event: sunset
    offset: -0:30
    platform: sun
  condition: []
  action:
    service: scene.turn_on
    entity_id: scene.film

- alias: Licht (minder gedimd) bij zonsondergang
  trigger:
    event: sunset
    offset: -0:00
    platform: sun
  condition: []
  action:
    service: scene.turn_on
    entity_id: scene.conversatie
