- alias: test_an_automation
  trigger:
    - platform: state
      entity_id: input_select.test
      to: 'Start'
  action:
    - service: shell_command.delete_old_camsnap
    - service: persistent_notification.create
      data_template:
        message: "Trigger: testselector op Start gezet. Shell_execute uitgevoerd"
        title: "Test an automation"


